# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-devel
warnings_are_errors: true
sudo: required
cache: packages

before_install:
  - sudo apt-get update
  - sudo apt-get install libnetcdf-dev

r_check_args: --no-tests
